apiVersion: v1
kind: ConfigMap
metadata:
    name: notification-config
data:
    SENDER_EMAIL: 'noreply@dasunsathsara.com'
    AUDIO_OUT_QUEUE: 'audio_out'
    GATEWAY_EXTERNAL_URL: 'https://gateway.yourdomain.com'
