apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: auth
    template:
        metadata:
            labels:
                app: auth
        spec:
            containers:
                - name: auth
                  image: dasunlk/mp3-converter-auth:latest
                  ports:
                      - containerPort: 8000
                  env:
                      - name: DATABASE_URL
                        value: 'postgresql+psycopg://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@auth-postgres-service:5432/$(POSTGRES_DB)'
                  envFrom:
                      - configMapRef:
                            name: auth-configmap
                      - secretRef:
                            name: auth-secret
